---
:verbose: false
:concurrency: 5
:timeout: 30

:queues:
  - default

:scheduler:
  :schedule:
    check_tasks:
      cron: '*/20 * * * * *'  # Every 20 seconds
      class: TaskExecutorWorker
      queue: default
